### PR TITLE
feat: adding missing translation

### PR DESCRIPTION
**Pull request by zmilan**
… and translations for new keys

added missing translation

"feat: #48"

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Baroshem — COMMENTED** [review]
Looks good to me. For now it probably wont work with Vendure as we do not have that functionality yet, but you can test it purely on the frontend to test if the locale selector works as expected. You can refer to the vue storefront commercetools demo -> https://demo-ct.vuestorefront.io/

**Comment by michaelbromley** [comment]
@Baroshem What is needed on the Vendure side for this to work?

**Comment by zmilan** [comment]
Hi @michaelbromley @Baroshem I got some busy week, so I wasn't able to check it more... I saw that some checks failed, so I'm not sure about it, but didn't get time to check it detailed. It looks like it is something about empty subject, but I'm not sure what exactly... I didn't contribute to the project before, so there is a big chance that I didn't do some steps correctly. Any help to unstuck me would be great... and would make my contribution faster :)

**Comment by Baroshem** [comment]
@michaelbromley what I meant by saying that it is not implemented yet, is that I have tot applied logic on VSF part to fetch current language from Vendure and also set new language from frontend to the Vendure server. So this was not implemented yet and I think we could create a separate issue for that for the Post MVP version.

@zmilan The only check that did not pass was the commitlint to validate PR. To fix it, the only thing you need to do is to create a pr title according to the commitlint (feat/docs/bug/etc). So in your case it will be `feat: adding missing translation
` (remember about lowercasing the first letter). 
Also, recently I have added a changelog to our project to more easily keep track of solved issues. Please update this file accordingly to other items -> https://github.com/vuestorefront/vendure/blob/develop/docs/changelog/1.0.0-beta.2.md

**Comment by Baroshem** [comment]
@zmilan 

Are you still working on this task? 

There are only small fixes needed for this PR to be merged 😉

**Comment by zmilan** [comment]
@Baroshem I have plan to try to complete this today. I have had to busy last two weeks and didn't get time to check it. I suppose I would be more useful once when I pass this child issues with tooling... I plan to contribute more to this project and Vendore in general soon.

**Comment by zmilan** [comment]
Hi @Baroshem, did I make it finally correct?

**Comment by Baroshem** [comment]
@zmilan 
Yes it is correct. One final step is to add a changelog here https://github.com/vuestorefront/vendure/blob/develop/docs/changelog/1.0.0-beta.3.md in a similar way as other points. If you do that, the PR is ready to be merged :)

**Comment by zmilan** [comment]
@Baroshem looks like I finally did it :dancers: I suppose from now it would be much easier for me... but I did a lot of mistakes during this PR

**Review by Baroshem — APPROVED** [review]
Nice work @zmilan !

**Comment by zmilan** [comment]
@Baroshem thanks... I will check some next one and try to be much more productive :)

**Pull request merged**
