### PR TITLE
feat: implementation of static pages

### PR DESCRIPTION
**Pull request by Michaeldrm**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Baroshem** [comment]
@Michaeldrm 

Amazing work!

Considering that it is ready I would like to have it in 1.0.0-beta.4 version instead of 1.1.0. Could you please create an entry in the changelog file (vendure/docs/changelog/1.0.0-beta.4.md) in a similar way that the other entries?

Also when you do that, make sure to run contributors:add in the root folder to add yourself to the contributors list and please also copy the newly created contributors to all README.md file and the docs so that you will be included everywhere :)

**Comment by Michaeldrm** [comment]
I'm very glad to contribute with this project! @Baroshem I did the best I could to do everything you asked me to but, if I did something wrong when adding me as a contributor or made some mistake when committing changes just let me know. I'm new to this git thing!

**Comment by Baroshem** [comment]
@Michaeldrm 

Two small things from me:

- Please, copy the generated contributors section to the REEADME.md files in all packages and also to the about.md in the docs folder
- It would be beneficial to have better naming convention for the commits. In this case I would recommend something like this `feat:

**Comment by Baroshem** [comment]
@Michaeldrm 

Are you able to edit your pull request accordingly to my suggestions? :) https://github.com/vuestorefront/vendure/pull/124#issuecomment-960486826

**Comment by Michaeldrm** [comment]
@Baroshem, sorry had a lot to do from work this weekend! I'm gonna try today. I'll let you know if I have any trouble.

**Comment by Michaeldrm** [comment]
@Baroshem, sorry I had some trouble making everything run again after formatting my computer, I tried to do everything you've asked but if I made some mistake feel free to tell me so I can do it right next time!

**Comment by Baroshem** [comment]
@Michaeldrm Everything good! One last thing, please run `yarn lint` to automatically lint your new files and that will be it. Awesome work!

After that, I will merge this Pr to the develop branch :)

**Comment by Michaeldrm** [comment]
@Baroshem Done!

**Review by Baroshem — APPROVED** [review]

**Comment by Baroshem** [comment]
Well done @Michaeldrm ! Welcome to our team!

**Pull request merged**
